# Copyright (c) 2024 Linaro LTD
# SPDX-License-Identifier: Apache-2.0

[package]
# This must be rustlet for now.
name = "rustlet"
version = "0.1.0"
edition = "2021"
description = "A sample hello world application in Rust"
license = "Apache-2.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
psa-crypto = { version = "0.12.0", default-features = false, features = ["operations"], git = "https://github.com/parallaxsecond/rust-psa-crypto.git", rev = "c076266423b0831935dcb871aaacb33ce376b8fd" }
