use core::ffi::c_void;

// FIXME: bindgen from generated manifest
pub const TFM_DP_SECRET_DIGEST_SIGNAL: u32 = 0x10;

// FIXME: bindgen from TF-M source tree
unsafe extern "C" {
    pub fn psa_panic();
    pub fn psa_wait(signal_mask: u32, timeout: u32) -> u32;
    pub fn psa_get(signal: u32, msg: &mut PsaMsg) -> i32;
    pub fn psa_reply(msg_handle: i32, status: i32);
    pub fn psa_read(msg_handle: i32, invec_idx: u32, buf: *mut u8, num_bytes: usize) -> usize;
    pub fn psa_hash_compute(
        alg: u32,
        input: *const u8,
        len: usize,
        hash: *mut u8,
        hash_size: usize,
        hash_len: *mut usize,
    ) -> i32;
    pub fn psa_write(msg_handle: i32, outvec_idx: u32, buf: *const u8, num_bytes: usize);
}

pub const PSA_WAIT_ANY: u32 = 0xFFFFFFFF;
pub const PSA_BLOCK: u32 = 0x80000000;
pub const PSA_IPC_CALL: i32 = 0;
pub const PSA_IPC_CONNECT: i32 = -1;
pub const PSA_IPC_DISCONNECT: i32 = -2;
pub const PSA_SUCCESS: i32 = 0;
pub const PSA_ERROR_PROGRAMMER_ERROR: i32 = -129;
pub const PSA_ERROR_INVALID_ARGUMENT: i32 = -135;
pub const PSA_ALG_SHA_256: u32 = 0x02000009;

pub const PSA_MAX_IOVEC: usize = 4;
#[derive(Default)]
#[repr(C, packed)]
pub struct PsaMsg {
    pub msg_type: i32, /* One of the following values:
                        * PSA_IPC_CONNECT
                        * >= 0
                        * PSA_IPC_DISCONNECT
                        */
    pub handle: i32, /* A reference generated by the SPM to the
                      * message returned by psa_get().
                      */
    pub client_id: i32, /* Partition ID of the sender of the
                         * message:
                         *  - secure partition id;
                         *  - non secure client endpoint id.
                         */
    pub rhandle: *mut c_void, /* Be useful for binding a connection to some
                               * application-specific data or function
                               * pointer within the RoT Service
                               * implementation.
                               */
    pub in_size: [usize; PSA_MAX_IOVEC], /* Provide the size of each client input
                                          * vector in bytes.
                                          */
    pub out_size: [usize; PSA_MAX_IOVEC], /* Provide the size of each client output
                                           * vector in bytes.
                                           */
}
