// Copyright (c) 2021 Nordic Semiconductor ASA
// Copyright (c) 2025 Dmitrii Sharshakov
// SPDX-License-Identifier: Apache-2.0

#![no_std]
#![no_main]

use core::{ffi::c_void, panic::PanicInfo};

// FIXME: bindgen from TF-M
unsafe extern "C" {
    fn psa_panic();
    fn psa_wait(signal_mask: u32, timeout: u32) -> u32;
    fn psa_get(signal: u32, msg: &PsaMsg) -> i32;
    fn psa_reply(msg_handle: i32, status: i32);
}

// FIXME: bindgen from TF-M
pub const PSA_WAIT_ANY: u32 = 0xFFFFFFFF;
pub const PSA_BLOCK: u32 = 0x80000000;
pub const PSA_IPC_CALL: i32 = 0;
pub const PSA_IPC_CONNECT: i32 = -1;
pub const PSA_IPC_DISCONNECT: i32 = -2;
pub const PSA_SUCCESS: i32 = 0;
pub const PSA_ERROR_PROGRAMMER_ERROR: i32 = -129;

// FIXME: bindgen from TF-M
pub const PSA_MAX_IOVEC: usize = 4;
#[derive(Default)]
#[repr(C, packed)]
pub struct PsaMsg {
    pub msg_type: i32, /* One of the following values:
                        * PSA_IPC_CONNECT
                        * >= 0
                        * PSA_IPC_DISCONNECT
                        */
    pub handle: i32, /* A reference generated by the SPM to the
                      * message returned by psa_get().
                      */
    pub client_id: i32, /* Partition ID of the sender of the
                         * message:
                         *  - secure partition id;
                         *  - non secure client endpoint id.
                         */
    pub rhandle: *mut c_void, /* Be useful for binding a connection to some
                               * application-specific data or function
                               * pointer within the RoT Service
                               * implementation.
                               */
    pub in_size: [usize; PSA_MAX_IOVEC], /* Provide the size of each client input
                                          * vector in bytes.
                                          */
    pub out_size: [usize; PSA_MAX_IOVEC], /* Provide the size of each client output
                                           * vector in bytes.
                                           */
}

// FIXME: bindgen from generated
pub const TFM_DP_SECRET_DIGEST_SIGNAL: u32 = 0x10;

#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    unsafe {
        psa_panic();
    }

    unreachable!()
}

fn dp_signal_handle(signal: u32) {
    let mut msg: PsaMsg = PsaMsg::default();

    let mut status = unsafe { psa_get(signal, &msg) };
    match msg.msg_type {
        PSA_IPC_CONNECT => {
            unsafe { psa_reply(msg.handle, PSA_SUCCESS) };
        }
        PSA_IPC_CALL => {
            // status = pfn(&msg);
            status = PSA_ERROR_PROGRAMMER_ERROR;
            unsafe { psa_reply(msg.handle, status) };
        }
        PSA_IPC_DISCONNECT => {
            unsafe { psa_reply(msg.handle, PSA_SUCCESS) };
        }
        _ => panic!(),
    }
}

#[no_mangle]
extern "C" fn tfm_dp_req_mngr_init() -> i32 {
    loop {
        let signals: u32 = unsafe { psa_wait(PSA_WAIT_ANY, PSA_BLOCK) };
        if signals & TFM_DP_SECRET_DIGEST_SIGNAL == TFM_DP_SECRET_DIGEST_SIGNAL {
            dp_signal_handle(TFM_DP_SECRET_DIGEST_SIGNAL);
        } else {
            panic!();
        }
    }
}
